
logo: 'assets/images/logo.png'

favicon: 'assets/images/favicon.ico'

name: "Software Developer Things"

title: ""

description: "I'll put something witty and clever here later."

baseurl: '/'

email: 'the.software.shinobi@gmail.com'

include: ["_pages"]

exclude: ["recycle-content"]

permalink: none

plugins: 

  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

  softwareshinobi:

    name: "Software Shinobi"

    display_name: "Software Shinobi"

    email: the.software.shinobi@gmail.com

    site: https://links.softwareshinobi.digital

    twitter: https://links.softwareshinobi.digital

    description: "Freelance Software Developer & Technical Writer. I design, code, test, document, and deploy software things."

    avatar: 'assets/images/valorant/softwareshinobi.jpg'

    bio: "Freelance Software Developer & Technical Writer. I design, code, test, document, and deploy software things."

  bohra:

    name: "Bohra"

    display_name: "Bohra" 
   
    avatar: 'assets/images/valorant/bohra.jpg'

    bio: "Troy's Assistant, I write about freelancing, making money online, and marketing."

  alexandria:

    name: "Alexandria"

    display_name: "Alexandria" 
   
    avatar: 'assets/images/valorant/alexandria.jpg'

    bio: "Hi guys! It's Alexandria. I write about career, job search, and mindfulness things."

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: softwareshinobi
      avatar: /assets/images/valorant/softwareshinobi.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax

markdown: kramdown

highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
