version: "3"

networks:

    gitea-network:
    
        external: false

services:

    gitea-server:

        container_name: gitea-server

        image: gitea/gitea:1.16.8

        restart: always

        environment:

            - USER_UID=1000
    
            - USER_GID=1000

        networks:

            - gitea-network

        volumes:

            - ./container-volume/gitea-server:/data

            - /etc/timezone:/etc/timezone:ro

            - /etc/localtime:/etc/localtime:ro

        ports:

          - "3000:3000"

          - "3022:22"
